version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/usr/src/app
      - /usr/local/bundle
    stdin_open: true
    tty: true
    command: bash
